import type { CardData, ColumnDef } from "./types";
import { daysFromNow } from "./dates";

export const COLUMNS: ColumnDef[] = [
  { id: "backlog", title: "Backlog" },
  { id: "in-progress", title: "In Progress" },
  { id: "cab", title: "Change Review (CAB)" },
  { id: "deployed", title: "Deployed" },
];

export function createSeedCards(): CardData[] {
  return [
    {
      id: "card-1",
      ticketId: "TASK-1005",
      title: "Refresh firmware inventory spreadsheet",
      category: "Planning",
      assignee: "AS",
      dueDate: daysFromNow(5),
      columnId: "backlog",
    },
    {
      id: "card-2",
      ticketId: "CHG-1090",
      title: "Decommission legacy VPN concentrator",
      category: "Network",
      priority: "P2",
      assignee: "JR",
      dueDate: daysFromNow(10),
      columnId: "backlog",
    },
    {
      id: "card-3",
      ticketId: "INC-2041",
      title: "Investigate intermittent Wi-Fi drops - Floor 3",
      category: "Incident",
      priority: "P2",
      assignee: "MK",
      dueDate: daysFromNow(1),
      columnId: "backlog",
    },
    {
      id: "card-4",
      ticketId: "CHG-1088",
      title: "Upgrade core switch firmware - DC2",
      category: "Network",
      priority: "P1",
      assignee: "TL",
      dueDate: daysFromNow(3),
      progress: 65,
      columnId: "in-progress",
    },
    {
      id: "card-5",
      ticketId: "TASK-1002",
      title: "Rotate service account credentials",
      category: "Security",
      assignee: "AS",
      dueDate: daysFromNow(2),
      progress: 30,
      columnId: "in-progress",
    },
    {
      id: "card-6",
      ticketId: "INC-2038",
      title: "Resolve VPN authentication failures",
      category: "Incident",
      priority: "P1",
      assignee: "JR",
      dueDate: daysFromNow(0),
      progress: 80,
      columnId: "in-progress",
    },
    {
      id: "card-7",
      ticketId: "CHG-1075",
      title: "Migrate DNS to new resolver cluster",
      category: "Network",
      priority: "P2",
      assignee: "MK",
      dueDate: daysFromNow(4),
      columnId: "cab",
    },
    {
      id: "card-8",
      ticketId: "CHG-1082",
      title: "Enable MFA enforcement org-wide",
      category: "Security",
      priority: "P1",
      assignee: "TL",
      dueDate: daysFromNow(6),
      columnId: "cab",
    },
    {
      id: "card-9",
      ticketId: "CHG-1050",
      title: "Patch edge firewalls - Q3 CVE batch",
      category: "Security",
      assignee: "JR",
      dueDate: daysFromNow(-2),
      columnId: "deployed",
    },
    {
      id: "card-10",
      ticketId: "CHG-1061",
      title: "Expand guest Wi-Fi capacity - HQ",
      category: "Network",
      assignee: "AS",
      dueDate: daysFromNow(-1),
      columnId: "deployed",
    },
    {
      id: "card-11",
      ticketId: "TASK-0998",
      title: "Decommission unused switch ports audit",
      category: "Planning",
      assignee: "MK",
      dueDate: daysFromNow(-12),
      columnId: "deployed",
    },
  ];
}
